.TH "repo.EdgeIterator" 3 "Thu Mar 31 2022" "GraphAssignment1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repo.EdgeIterator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, vertex_list)"
.br
.ti -1c
.RI "def \fB__iter__\fP (self)"
.br
.ti -1c
.RI "def \fB__next__\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlist\fP"
.br
.ti -1c
.RI "\fBvalue\fP"
.br
.ti -1c
.RI "\fBend\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This class is an iterator, iterating over a list representing inbound or outbound edges

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for GraphAssignment1 from the source code\&.
